### ISSUE TITLE
Adjusting

### ISSUE THREAD

**Issue by TopiNNN** [Hchong16/lost-ark-excavation-minigame#4]
Hi, so I cannot figure it our =] It is pressing space to late, I've read the notepad and I got it to 1 by 1 till 20, the standard is 13.
Still pressing it to late.
Also did the 80% hub thingy.

**Comment by Hchong16** [comment]
Hello! Apologies for the pain in setting up the program. Since the tool is not interacting with any game files, the program will definitely function differently on a case by case basis (i.e. different PC specs, latency, etc.). 

If it is pressing too **late**, you have a couple of options (combine a few together and it may work):
- Increasing the `starting_delay_seconds` (up to 10 max).
- Increase the `arrow_middle_offset` and/or `target_range_left_offset` (ignore the right offset). 

Also, make sure you have a purple shovel with level 2 difficulty reduction, this is ideal. Level 3 is too expensive and is unnecessary).

Let me know how this goes!
